### ISSUE TITLE
ValueError: 'a' must be 1-dimensional or an integer

### ISSUE THREAD

**Issue by andrestoga** [boschresearch/pcg_gazebo_pkgs#51]
Hi,

When trying to run "rosrun pcg_examples test_world_gen_examples.py" I'm getting the following error:

```
andrestoga@andrestoga-PC-US-HOME:~/ros/world_generator$ rosrun pcg_examples test_world_gen_examples.py 
Traceback (most recent call last):
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_examples/test/test_world_gen_examples.py", line 20, in <module>
    from pcg_gazebo.generators import WorldGenerator
  File "/home/andrestoga/ros/world_generator/devel/lib/python2.7/dist-packages/pcg_gazebo/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 34, in <module>
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/generators/__init__.py", line 18, in <module>
    from . import engines
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/generators/engines/__init__.py", line 18, in <module>
    from .engine import Engine
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/generators/engines/engine.py", line 16, in <module>
    from ..constraints import create_constraint
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/generators/constraints/__init__.py", line 18, in <module>
    from .tangent_constraint import TangentConstraint
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/generators/constraints/tangent_constraint.py", line 15, in <module>
    from ...log import PCG_ROOT_LOGGER
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/log.py", line 28, in <module>
    ''.join(random.choice(string.ascii_letters) for i in range(3))))
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/log.py", line 28, in <genexpr>
    ''.join(random.choice(string.ascii_letters) for i in range(3))))
  File "/home/andrestoga/.local/lib/python2.7/site-packages/pcg_gazebo/random.py", line 48, in choice
    return PCG_RANDOM_STATE.choice(*args, **kwargs)
  File "mtrand.pyx", line 1117, in mtrand.RandomState.choice
ValueError: 'a' must be 1-dimensional or an integer
```

Best,

**Comment by ralph-lange** [comment]
This repo is superseded by https://github.com/boschresearch/pcg_gazebo.
