### ISSUE TITLE
Traceback while running the mesh example

### ISSUE THREAD

**Issue by andrestoga** [boschresearch/pcg_gazebo_pkgs#52]
Hi,

I'm getting the following traceback while running the mesh example from the Model generator tutorial:

Traceback (most recent call last):
  File "/home/andrestoga/ros/world_generator/src/packages/testing/scripts/testing.py", line 163, in <module>
    create_and_spawn(config)
  File "/home/andrestoga/ros/world_generator/src/packages/testing/scripts/testing.py", line 39, in create_and_spawn
    models = create_models_from_config(config)
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/generators/creators.py", line 867, in create_models_from_config
    results = results + config2models(c)
  File "/home/andrestoga/ros/world_generator/src/packages/pcg_gazebo_pkgs/pcg_libraries/src/pcg_gazebo/generators/creators.py", line 830, in config2models
    models.append(mesh(**config['args']))
TypeError: mesh() got an unexpected keyword argument 'visual_mesh_filename'

Best,

**Comment by musamarcusso** [comment]
Hi, I transferred this project mostly to this Python project https://github.com/boschresearch/pcg_gazebo. You can also install it as `sudo pip3 install pcg-gazebo`. Please let me know if the errors persist with that installation.

**Comment by ct2034** [comment]
This repo is deprecated.
